# Project information
site_name: 'KotmolPdbParser'
site_description: 'A Protein Database (PDB) Parser written in Kotlin'
site_author: 'Jim Andreas'
site_url: 'https://kotmol.github.io/KotmolPdbParser'

# Repository
repo_name: 'kotmol/KotmolPdbParser'
repo_url: 'https://github.com/kotmol/KotmolPdbParser'

# Copyright
copyright: 'Copyright &copy; 2020 Jim Andreas'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/kotmol'
    - type: 'twitter'
      link: 'https://twitter.com/jimandreasdev'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/jimandreas'

# Google Analytics
#google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta

# Page tree
nav:
  - Home: index.md
  - Testing: Testing.md
  - Uploading: Uploading.md
  - PDB Notes: PDBnotes.md
    - Special Residues: Special Residues.md

